### ISSUE TITLE
About deploying more than 1 project

### ISSUE THREAD

**Issue by mozgbrasil** [Stremio/stremio-beamup-cli#2]
Hello my friends, Good afternoon, can you help me

I created 3 projects but when I update in 1 project it is updated in both according to the following report

Below I demonstrate the steps I took

1)

Below I demonstrate the commands and configuration used

	$ beamup
	Project Name (default: stremio-addon): 
	Project configuration saved at "/home/codespace/workspace/stremio-addon/beamup.json"
	error: remote beamup already exists.
	Do you want to deploy "stremio-addon"? (y/n): y
	Deploying to 9b7c457c25d2-stremio-addon.baby-beamup.club
	
Being returned

	=====> Application deployed:
		   http://9b7c457c25d2-stremio-addon.baby-beamup.club

	To a.baby-beamup.club:9b7c457c25d2/stremio-addon
	   1d105b0..75a040c  HEAD -> master
	Project URL: 9b7c457c25d2-stremio-addon.baby-beamup.club
	
2)

Below I demonstrate the commands and configuration used

	$ git remote -v
	beamup  dokku@a.baby-beamup.club:9b7c457c25d2/stremio-addon (fetch)
	beamup  dokku@a.baby-beamup.club:9b7c457c25d2/stremio-addon (push)
	origin  git@github.com:mozgbrasil/stremio-addon.git (fetch)
	origin  git@github.com:mozgbrasil/stremio-addon.git (push)

	$ git remote rm beamup

	$ git remote -v
	origin  git@github.com:mozgbrasil/stremio-addon.git (fetch)
	origin  git@github.com:mozgbrasil/stremio-addon.git (push)

	$ rm beamup.json

	$ beamup deploy
	Project Name (default: stremio-addon): stremio-addon-tmdb
	Project configuration saved at "/home/codespace/workspace/stremio-addon/beamup.json"
	Do you want to deploy "stremio-addon-tmdb"? (y/n): y
	Deploying to 9b7c457c25d2-stremio-addon-tmdb.baby-beamup.club

Being returned

	=====> Application deployed:
		   http://9b7c457c25d2-stremio-addon-tmdb.baby-beamup.club

	To a.baby-beamup.club:9b7c457c25d2/stremio-addon-tmdb
	   710d285..75a040c  HEAD -> master
	Project URL: 9b7c457c25d2-stremio-addon-tmdb.baby-beamup.club

3)

When accessing

https://9b7c457c25d2-stremio-addon.baby-beamup.club/
https://9b7c457c25d2-stremio-addon-tmdb.baby-beamup.club/
https://9b7c457c25d2-stremio-addon-cinemeta.baby-beamup.club/

We see that the same information is displayed

A different description should be displayed for each environment

4)

Refiz as seguintes implantação para ambos ambiente mas a ocorre persiste

```
# nano package.json 
	# update description
	Deploying 16/02/2021 19:27:07 (stremio-addon)
	Deploying 16/02/2021 19:33:36 (stremio-addon-tmdb)
	Deploying 16/02/2021 19:47:14 (stremio-addon-cinemeta)
# git push origin master

clear
ls
git remote -v
git remote rm beamup
git remote -v
rm beamup.json
beamup deploy
```

5)

How do I delete the following deployment ?

https://9b7c457c25d2-stremio-addon.baby-beamup.club/

I intend to leave only the following 

https://9b7c457c25d2-stremio-addon-tmdb.baby-beamup.club/
https://9b7c457c25d2-stremio-addon-cinemeta.baby-beamup.club/

# ##

**Comment by jaruba** [comment]
This is the wrong place to ask this, this is only the CLI, the beamup server issues are here:
https://github.com/Stremio/stremio-beamup/issues

As for deleting a project, you will also need to make an issue for the beamup server, this is explained in the FAQ:
https://github.com/Stremio/stremio-beamup-cli/wiki/FAQ

**Comment by zestyoutofzestyist** [comment]
HOW THO

**Comment by dexter21767-dev** [comment]
@zestyoutofzestyist create a new issue on [stremio-beamup](https://github.com/Stremio/stremio-beamup/issues) and i will do my best to help
