### ISSUE TITLE
 remove project from BeamUp

### ISSUE THREAD

**Issue by mozgbrasil** [Stremio/stremio-beamup-cli#3]
Good morning my friend

According

https://github.com/Stremio/stremio-beamup-cli/issues/2

I kindly ask you to exclude the following service that is published

https://9b7c457c25d2-stremio-addon.baby-beamup.club/

**Comment by jaruba** [comment]
As I mentioned in the other issue and is also noted in the [FAQ](https://github.com/Stremio/stremio-beamup-cli/wiki/FAQ), requests for the removal of a project from the beamup server go to the beamup repo, not the CLI repo, the beamup repo is located here: https://github.com/Stremio/stremio-beamup/issues
