### ISSUE TITLE
Stremio addon project ip adress

### ISSUE THREAD

**Issue by osmansonsuz** [Stremio/stremio-beamup-cli#4]
I need know my project ip adress.I am using oracle database.I need to specify an ip adress to connect database.How can i find my project ip adress ?
![image](https://github.com/Stremio/stremio-beamup-cli/assets/77057974/0dac714a-94a5-4136-a849-99422400c3a1)

**Comment by dexter21767-dev** [comment]
there's no straight forward way for doing that, 
but you can make a simple script 
that has an endpoint that makes an HTTP request to some "what's my IP" website and prints the result on the webpage. 
then right after u get the IP address revert the changes and update your addon to remove the endpoint.

**Comment by osmansonsuz** [comment]
> there's no straight forward way for doing that, but you can make a simple script that has an endpoint that makes an HTTP request to some "what's my IP" website and prints the result on the webpage. then right after u get the IP address revert the changes and update your addon to remove the endpoint.

I have decided to deploy my addon with other deployment methods. Thank you.
