### ISSUE TITLE
project not pulling latest code 

### ISSUE THREAD

**Issue by dsoh** [Stremio/stremio-beamup-cli#5]
i am using beamup to deploy my latest code it looks successful and even shows the correct hash

`6a0ae8c..059a1c4  HEAD -> master`

however once the server comes up the manifest is old and still stays at 0.0.1 when its been updated to be 0.0.2.

locally when i run npm run start it seems to work fine, is there anything else that needs to be done to update and restart?

**Comment by jaruba** [comment]
this is due to heavy caching, it will take some time for the cache to be invalidated for the manifest file

**Comment by dsoh** [comment]
thank you for the information will close this
